use content_mgmt;
INSERT INTO STATES (stateName, shortCode) VALUES ('Alabama', 'AL');
INSERT INTO STATES (stateName, shortCode) VALUES ('Alaska', 'AK');
INSERT INTO STATES (stateName, shortCode) VALUES ('Arizona', 'AZ');
INSERT INTO STATES (stateName, shortCode) VALUES ('Arkansas', 'AR');
INSERT INTO STATES (stateName, shortCode) VALUES ('California', 'CA');
INSERT INTO STATES (stateName, shortCode) VALUES ('Colorado', 'CO');
INSERT INTO STATES (stateName, shortCode) VALUES ('Connecticut', 'CT');
INSERT INTO STATES (stateName, shortCode) VALUES ('Delaware', 'DE');
INSERT INTO STATES (stateName, shortCode) VALUES ('Florida', 'FL');
INSERT INTO STATES (stateName, shortCode) VALUES ('Georgia', 'GA');
INSERT INTO STATES (stateName, shortCode) VALUES ('Hawaii', 'HI');
INSERT INTO STATES (stateName, shortCode) VALUES ('Idaho', 'ID');
INSERT INTO STATES (stateName, shortCode) VALUES ('Illinois', 'IL');
INSERT INTO STATES (stateName, shortCode) VALUES ('Indiana', 'IN');
INSERT INTO STATES (stateName, shortCode) VALUES ('Iowa', 'IA');
INSERT INTO STATES (stateName, shortCode) VALUES ('Kansas', 'KS');
INSERT INTO STATES (stateName, shortCode) VALUES ('Kentucky', 'KY');
INSERT INTO STATES (stateName, shortCode) VALUES ('Louisiana', 'LA');
INSERT INTO STATES (stateName, shortCode) VALUES ('Maine', 'ME');
INSERT INTO STATES (stateName, shortCode) VALUES ('Maryland', 'MD');
INSERT INTO STATES (stateName, shortCode) VALUES ('Massachusetts', 'MA');
INSERT INTO STATES (stateName, shortCode) VALUES ('Michigan', 'MI');
INSERT INTO STATES (stateName, shortCode) VALUES ('Minnesota', 'MN');
INSERT INTO STATES (stateName, shortCode) VALUES ('Mississippi', 'MS');
INSERT INTO STATES (stateName, shortCode) VALUES ('Missouri', 'MO');
INSERT INTO STATES (stateName, shortCode) VALUES ('Montana', 'MT');
INSERT INTO STATES (stateName, shortCode) VALUES ('Nebraska', 'NE');
INSERT INTO STATES (stateName, shortCode) VALUES ('Nevada', 'NV');
INSERT INTO STATES (stateName, shortCode) VALUES ('New Hampshire', 'NH');
INSERT INTO STATES (stateName, shortCode) VALUES ('New Jersey', 'NJ');
INSERT INTO STATES (stateName, shortCode) VALUES ('New Mexico', 'NM');
INSERT INTO STATES (stateName, shortCode) VALUES ('New York', 'NY');
INSERT INTO STATES (stateName, shortCode) VALUES ('North Carolina', 'NC');
INSERT INTO STATES (stateName, shortCode) VALUES ('North Dakota', 'ND');
INSERT INTO STATES (stateName, shortCode) VALUES ('Ohio', 'OH');
INSERT INTO STATES (stateName, shortCode) VALUES ('Oklahoma', 'OK');
INSERT INTO STATES (stateName, shortCode) VALUES ('Oregon', 'OR');
INSERT INTO STATES (stateName, shortCode) VALUES ('Pennsylvania', 'PA');
INSERT INTO STATES (stateName, shortCode) VALUES ('Rhode Island', 'RI');
INSERT INTO STATES (stateName, shortCode) VALUES ('South Carolina', 'SC');	
INSERT INTO STATES (stateName, shortCode) VALUES ('South Dakota', 'SD');
INSERT INTO STATES (stateName, shortCode) VALUES ('Tennessee', 'TN');
INSERT INTO STATES (stateName, shortCode) VALUES ('Texas', 'TX');
INSERT INTO STATES (stateName, shortCode) VALUES ('Utah', 'UT');
INSERT INTO STATES (stateName, shortCode) VALUES ('Vermont', 'VT');
INSERT INTO STATES (stateName, shortCode) VALUES ('Virginia', 'VA');
INSERT INTO STATES (stateName, shortCode) VALUES ('Washington', 'WA');
INSERT INTO STATES (stateName, shortCode) VALUES ('West Virginia', 'WV');
INSERT INTO STATES (stateName, shortCode) VALUES ('Wisconsin', 'WI');
INSERT INTO STATES (stateName, shortCode) VALUES ('Wyoming', 'WY');